from db import init_db, get_db, dumps, audit

recommendations = [
    dict(title='Enforce MFA for privileged accounts', summary='18 privileged admin accounts are still signing in without multi-factor approval.', severity='High', confidence_score=94, confidence_label='High confidence', confidence_reason='The AI is confident because the same risky sign-in pattern appeared repeatedly across privileged accounts.', status='Pending', affected_count=18, category='Identity Security', reasoning_steps=[{'step':'Risk pattern found','detail':'Privileged accounts are accessing sensitive areas without an added verification step.'},{'step':'Business context checked','detail':'These accounts can change policies, users, and device rules.'},{'step':'Recommended action selected','detail':'Enforcing MFA reduces account takeover risk with limited disruption.'}], evidence=['18 admin accounts without MFA','6 risky sign-ins in 14 days','2 access attempts from unusual locations'], data_sources=['Identity sign-in logs from the last 14 days','Privileged role membership list','Conditional access policy records'], limitations=['The AI cannot confirm whether every sign-in was approved by a manager offline.','Temporary emergency admin accounts may need exception handling.'], alternatives=['Enable MFA only for global admins first','Start with a 3-day warning period','Escalate to identity team for manual review'], agent_flow=[{'title':'Detection agent','detail':'Found privileged accounts missing MFA.'},{'title':'Risk scoring agent','detail':'Compared sign-in behavior and account privilege level.'},{'title':'Remediation agent','detail':'Suggested staged MFA enforcement.'}], approve_impact='MFA policy is prepared for privileged accounts and risk of account takeover is reduced.', reject_impact='Privileged accounts remain exposed to password-only compromise.', business_impact='Low disruption if admins are notified before enforcement.', security_impact='High security improvement.', disruption_level='Medium', recommended_path='Approve with a 24-hour admin notification window.'),
    dict(title='Patch critical Windows vulnerability', summary='246 Windows endpoints are missing a critical security update.', severity='Critical', confidence_score=89, confidence_label='High confidence', confidence_reason='The AI is confident because device inventory and patch records agree that the update is missing.', status='Pending', affected_count=246, category='Patch Management', reasoning_steps=[{'step':'Patch gap detected','detail':'A critical update is missing on many active endpoints.'},{'step':'Exposure checked','detail':'Several affected devices are used daily and connect to company services.'},{'step':'Rollout plan selected','detail':'A phased rollout lowers risk while closing the vulnerability.'}], evidence=['246 devices missing patch KB-5039999','192 devices active in last 7 days','No compatibility block found for most models'], data_sources=['Device inventory','Patch compliance records','Endpoint health telemetry'], limitations=['Some users may be offline during rollout.','A few older models may need manual validation.'], alternatives=['Patch pilot group first','Schedule overnight rollout','Escalate unsupported devices'], agent_flow=[{'title':'Inventory agent','detail':'Matched device model and OS version.'},{'title':'Patch agent','detail':'Detected missing critical update.'},{'title':'Rollout agent','detail':'Recommended phased deployment.'}], approve_impact='Critical patch rollout begins in waves and reduces exposure.', reject_impact='Devices remain vulnerable and may trigger repeated security alerts.', business_impact='Moderate disruption because restarts may be required.', security_impact='Very high security improvement.', disruption_level='Medium-high', recommended_path='Approve phased rollout to pilot group, then expand.'),
    dict(title='Remove stale guest access', summary='42 guest accounts have not signed in for over 90 days but still have workspace access.', severity='Medium', confidence_score=76, confidence_label='Review recommended', confidence_reason='The AI has good evidence, but some guests may still be part of long-running projects.', status='Pending', affected_count=42, category='Access Control', reasoning_steps=[{'step':'Inactive guests detected','detail':'Guest accounts are unused but retain access.'},{'step':'Access level reviewed','detail':'Several accounts can still view project files.'},{'step':'Safer cleanup proposed','detail':'Remove stale access after manager notice.'}], evidence=['42 guests inactive for 90+ days','17 have access to project folders','No recent collaboration activity'], data_sources=['Guest account directory','Workspace access logs','File sharing records'], limitations=['Some projects may be paused rather than complete.','The AI cannot know every manager’s verbal approval.'], alternatives=['Notify owners before removal','Disable instead of delete','Remove access only from sensitive folders'], agent_flow=[{'title':'Access agent','detail':'Found stale guest accounts.'},{'title':'Context agent','detail':'Checked recent collaboration activity.'},{'title':'Cleanup agent','detail':'Suggested owner-notified removal.'}], approve_impact='Stale external access is removed after owner notice.', reject_impact='Dormant accounts keep unnecessary access.', business_impact='Low disruption if owners get warning.', security_impact='Medium security improvement.', disruption_level='Low', recommended_path='Approve with owner notification.'),
    dict(title='Retire inactive device records', summary='137 inactive device records are cluttering compliance views.', severity='Low', confidence_score=68, confidence_label='Review recommended', confidence_reason='The AI suggests cleanup, but some devices may be in storage or repair.', status='Pending', affected_count=137, category='Device Hygiene', reasoning_steps=[{'step':'Inactive records found','detail':'Devices have not checked in recently.'},{'step':'Compliance noise checked','detail':'Inactive records make dashboards harder to read.'},{'step':'Cleanup suggested','detail':'Retire only after asset owner review.'}], evidence=['137 devices inactive for 120+ days','83 listed as non-compliant due to stale check-in','No recent security signal'], data_sources=['Device inventory','Compliance dashboard','Asset ownership list'], limitations=['Some devices may be offline intentionally.','Asset tags may be outdated.'], alternatives=['Archive records','Ask owners to confirm','Retire only devices older than 180 days'], agent_flow=[{'title':'Hygiene agent','detail':'Found inactive records.'},{'title':'Ownership agent','detail':'Matched likely device owners.'},{'title':'Cleanup agent','detail':'Suggested cautious retirement.'}], approve_impact='Inactive devices are retired from active compliance views.', reject_impact='Compliance dashboards remain noisy.', business_impact='Very low disruption.', security_impact='Low security improvement, high clarity improvement.', disruption_level='Low', recommended_path='Approve for devices inactive over 180 days first.'),
    dict(title='Quarantine suspicious endpoint', summary='One endpoint shows unusual activity that may indicate compromise.', severity='Critical', confidence_score=61, confidence_label='Low confidence', confidence_reason='The AI sees risky behavior, but there is not enough evidence to act without analyst review.', status='Pending', affected_count=1, category='Endpoint Security', reasoning_steps=[{'step':'Unusual endpoint behavior found','detail':'The device contacted rare external destinations and changed startup settings.'},{'step':'Confidence checked','detail':'Only one device is affected and the signal could be a false alarm.'},{'step':'Cautious action recommended','detail':'Escalate or isolate with admin confirmation.'}], evidence=['Rare outbound connection observed','Startup setting changed unexpectedly','Endpoint health score dropped'], data_sources=['Endpoint telemetry','Network connection summary','Device health signals'], limitations=['The AI cannot confirm whether a technician made the change.','Network destination reputation may change over time.'], alternatives=['Escalate to security analyst','Collect more logs first','Temporarily restrict network access instead of full quarantine'], agent_flow=[{'title':'Detection agent','detail':'Flagged unusual behavior.'},{'title':'Threat context agent','detail':'Compared signals with known risky patterns.'},{'title':'Safety agent','detail':'Recommended human review before quarantine.'}], approve_impact='Device is isolated from the network while security reviews it.', reject_impact='A potentially compromised endpoint remains connected.', business_impact='High disruption for the device owner.', security_impact='Potentially high, but confidence is limited.', disruption_level='High', recommended_path='Escalate before full quarantine unless activity increases.')
]

incidents = [dict(title='Quarantine recommendation reviewed safely', what_happened='The AI suggested quarantining one device with limited evidence.', why='Endpoint behavior looked suspicious but could also be a technician change.', safeguard='Human confirmation stopped automatic quarantine.', human_decision='Escalated to security analyst for deeper review.', prevention='Require at least two strong signals before showing quarantine as primary action.')]

usability = [
 ('P1', 90, '1m 20s', 'Wanted clearer confidence wording', 'Added plain confidence reason below every badge'),
 ('P2', 80, '1m 55s', 'Missed limitations section', 'Moved limitations into a brighter card'),
 ('P3', 100, '1m 05s', 'Understood decision path quickly', 'Kept approval modal concise'),
 ('P4', 80, '2m 10s', 'Asked what data sources meant', 'Added source labels in simple language'),
 ('P5', 90, '1m 34s', 'Wanted audit proof', 'Added searchable audit timeline')
]

def seed():
    init_db(); conn=get_db(); cur=conn.cursor()
    if cur.execute('SELECT COUNT(*) FROM recommendations').fetchone()[0] == 0:
        for r in recommendations:
            cur.execute('''INSERT INTO recommendations(title,summary,severity,confidence_score,confidence_label,confidence_reason,status,affected_count,category,reasoning_steps,evidence,data_sources,limitations,alternatives,agent_flow,approve_impact,reject_impact,business_impact,security_impact,disruption_level,recommended_path) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)''',
            (r['title'],r['summary'],r['severity'],r['confidence_score'],r['confidence_label'],r['confidence_reason'],r['status'],r['affected_count'],r['category'],dumps(r['reasoning_steps']),dumps(r['evidence']),dumps(r['data_sources']),dumps(r['limitations']),dumps(r['alternatives']),dumps(r['agent_flow']),r['approve_impact'],r['reject_impact'],r['business_impact'],r['security_impact'],r['disruption_level'],r['recommended_path']))
        cur.execute("INSERT OR REPLACE INTO settings(key,value) VALUES('autonomy','Always ask me')")
        for i in incidents: cur.execute('INSERT INTO incidents(title,what_happened,why,safeguard,human_decision,prevention) VALUES(?,?,?,?,?,?)', tuple(i.values()))
        for u in usability: cur.execute('INSERT INTO usability_results(participant,comprehension,decision_time,confusion,improvement) VALUES(?,?,?,?,?)', u)
        conn.commit(); audit('TrustLens AI','Generated initial recommendations','All recommendations','AI','Completed','','AI prepared transparent recommendation cards for admin review.')
    conn.close()

if __name__ == '__main__':
    seed(); print('Seed complete. Database ready.')
